# Generated by Django 5.1.7 on 2025-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
    ]
