# Generated by Django 4.2.7 on 2025-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_is_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenthistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("edit", "Редактирование"),
                    ("create", "Создание"),
                    ("view", "Просмотр"),
                    ("share", "Предоставление доступа"),
                    ("revoke", "Отзыв доступа"),
                    ("title_change", "Изменение заголовка"),
                ],
                default="edit",
                max_length=20,
            ),
        ),
    ]
