# Generated by Django 4.2.7 on 2025-04-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_documenthistory_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenthistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("edit", "Редактирование"),
                    ("create", "Создание"),
                    ("view", "Просмотр"),
                    ("share", "Предоставление доступа"),
                    ("revoke", "Отзыв доступа"),
                    ("title_change", "Изменение заголовка"),
                    ("nested_create", "Создание вложенного документа"),
                ],
                default="edit",
                max_length=20,
            ),
        ),
    ]
